name: "Deploy Meetsy to Github Pages"

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:

  build:
    name: "Build Meetsy"
    uses: ./.github/workflows/ci-build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Setup Github Pages"
        uses: actions/configure-pages@v5

      - name: "Download build"
        uses: actions/download-artifact@v4
        with:
          name: 'page'
          path: .

      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: "Deploy to GitHub Pages"
        uses: actions/deploy-pages@v4